### ISSUE TITLE
docker-compose中无法识别多个域名

### ISSUE THREAD

**Issue by qinqoushui** [xiaojun207/docker-nginx#4]
```
 nginx:
    image: xiaojun207/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dist:/data/dist
      - ./pkg:/data/pkg
      - ./nginx/logs:/var/log/nginx
      - "./nginx/web:/data/web"
      - "./nginx/nginx/ssl:/etc/nginx/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d"
      - "./nginx/acme_cert:/acme_cert"
    environment:
      - SslDomains=pro.xjrfid.com;lic.xjrfid.com
      - SslServer=letsencrypt
      - mail=zhagnwenxiang@zyactech.com
    restart: always
```
不知道如何编写，目前会把整个字符串当成一个域名
